apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: machine-user
spec:
  encryptedData:
    token: AgARMX4r8zOpHb+u0F6YwYhClS29EeQnf70iZZaxQSnL8tkkCb99knsOYUXFjtpxz/XgiNv4PUDKSZOYqjR/dFTNrEaUkgyshK+U84lH1exIkddXC9UMwwU4G4vukdb1WiP4Hdoxwrr0Bjn3QaFTeWatYn7K9zpoH0Zh8VH6Q5PQSM9NmvVjL3gOqGUg22XkhPSMYgFrE5ws7g1PNxZS2ZGMLhXsKAcN+GIiJWxalABcX6KoCqyPtI983UW1yqz/IVOqaR+gd2z3Gd5nRLkNa8nl7sbsPGKTimi979eLonv2or/Ye8MGS6Kc5d1Nw9pPmYk37Z9TxHAwyyqT8Clw2uv93Y7Ubu97sk1xpVl5IxY5c57Hm3cZ4mjQhU0/lnczZlLgXWHf3anGrHkzJUivqV/SGjz+8Ed2jzjS1hh+IVHQIFdRxPSLMDRXmRHtgpgDEMWyi36F9VNkFUtoYRWVF+BdGRtUlD9OKvb9dY+VLNcXfjtYR2UN78wm1UZE/SfwosEGtZTdiOpyC2+ddOB5wjBveueFH0imhiaw9M8+sk5dZFeVHpoW0T/EeSyC4e9nWU+EFOywh9vUGnbcanatKglHvJwHNQWk3j1RACj9AJqn2+i04jkQR4rW4qiIds4a6NdxV+JBBf0kmUGMIMlwMq6Ok6PE9auwoKyk0MqqogcxG047FEFr2xJr3lvP+gnazH75mnWvUiUQqNK71MhjEuJZ1F1XhLp0snOyIkPda/CPcrKyDeyfmCj4
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: machine-user

