apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: ibm-entitlement-key
spec:
  encryptedData:
    .dockerconfigjson: AgB7YIP3m1z4vuQOw0sb+pokqcO4uj5qxna/P8DyV1c2ydFFC4M01J5x3q6GsfrS2xHFL3TtiAqOzgF0Kb6nQRD/Sd7Z8GBe2K+/wS2M5epgti4iJPG0X4EtQST9QHDE0ZfctAYcT4xDSfu84EV5OExRYvzfjaDItPzlehJUMUZbryIkz60eu5nVPtpMsBhGtVUBnkiQ70y+4MKOdRf9jqdAqC9s6+supAg0TQf8UfKgp2x6i4UUbaE2+/sp6fWjEKnVdGQsQm87luwJ3axDbC4+BUngl2+mHPqKqJ6IhP4qYZPdR4k5cptp3up+2tSmWktrRU96YL0CnSdTLkoKtX1f1nC03+66l7lab+Dn2lSdDM9pGWjZLjSf6Y12FBNqTMQvU3j8YZy8zsuoESvHd0c/uO7akc6v2Bk9p6af8TJM1/afTt4fM5Zk1WnqG76xa7mraedHkrWvXQFTswvLQjVy53WGI7pHY3o9sSoKTeAYiwMbF40I5vR8o0I5raP1fPfEXmzep4AVJkTtkPkoxnkVblZrz2wmc4RI5XHM/kBj44y0kQwz9VP6q74+sL7d/LDNsyk+cKzo6SFwWoG9nKVBFThKNl4+LDUHrElmnwQdyNnN2/8PACtIjY5Qs5e0mQtbmWW2ED0LEPx01WO95asP3VxqP0dPBi0Bdz4tB9DZgb+HVlpL9tX3lWyjYlW0Bqc482rY2vRYL6gonK+3CRYv9wtYspfm+PSLmAyObpxjZJdXO7JIHP6qxMs6NMCaLpwF8EEE7DbrJxQjjP650CBCrSJAa9ZfAIxQ668o9AZqV5HhAgeTAuDtGymDA3vwUh8ZzPZ1XdnKCEfLPM2n0/HY+t0T9OTuAHAad94dHwB/CYKjTH5NXHWhf2B4G2QFcrf54Jlt7mCvW7hD8uNHNl/+95JC0r2Taec/hLbZXLP3ynNPs+oai3bmhcYxdnmIkHcNGoeCLfqdAkmOub2B10jVOqGOMIjW7uHw9jf0x+3DI1g+QepIgGCvHYb+QLkIGxZR8QqkigwcJhbWB9AG8te+SYOhbyF9nsoE4TMlRG2kWvERS7PyTjWhwDC/Svu/4Fb0Udq2VnWMr4xgmtZQURxf/0Q0lkhEnDQskw8uSONa1TnC4omxaJgZ9pxDguBRwD/j6lErRdtijYBk5Y5KsyAIOMbPxFgR2Qf3ZLcRoYpbhgcwyEz3pWYF2Nz3yDB8+fqjubR4Qp+fYTqGG2DEEfcVuYjuin1Cx/5tAFQG2Kohq8Rq+c04EiGnqUzz9Z56wNn3Gwk94gUN2SVIMwyaae2iXkA3+nOx2tB34NKZkv1q/8wXLSMm7trZhwnibBpcER+q
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      labels:
        created-by: pipeline
      name: ibm-entitlement-key
    type: kubernetes.io/dockerconfigjson

