apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: create-customer-policy
spec:
  type: policyproject
  contents: UEsDBAoAAAAAAPGqdlYAAAAAAAAAAAAAAAAXABwAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9VVAkAA9VxG2T9cRtkdXgLAAEEAAAAAAQAAAAAUEsDBBQACAAIAPGqdlYAAAAAAAAAAPIAAAArABwAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9iYWNrZW5kdXJsLnBvbGljeXhtbFVUCQAD1XEbZNVxG2R1eAsAAQQAAAAABAAAAABdjjsOwjAMhndOEWVvU7aq6mMBRqZygJAYiEidKE4LvT2pCkIwWfb/8Fd3z8GyCQIZhw3f5gVngMppg9eGn/pDVvKu3dTeWaMMULthbF1mto5+9pCcBGEHF4Og+Vs4yiEJZ6nugHoM9nPvYfBWxr/QUpyqyUm/R+2dwdjeYvSVEMstORNkhg4J1Bggj85ZymlSVVmUhXhQLX6yC6dYHyZ88eV/AVBLBwgyw5h4pAAAAPIAAABQSwECHgMKAAAAAADxqnZWAAAAAAAAAAAAAAAAFwAYAAAAAAAAABAA7UEAAAAAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9VVAUAA9VxG2R1eAsAAQQAAAAABAAAAABQSwECHgMUAAgACADxqnZWMsOYeKQAAADyAAAAKwAYAAAAAAABAAAApIFRAAAAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9iYWNrZW5kdXJsLnBvbGljeXhtbFVUBQAD1XEbZHV4CwABBAAAAAAEAAAAAFBLBQYAAAAAAgACAM4AAABqAQAAAAA=
