apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: create-customer-policy
spec:
  type: policyproject
  contents: UEsDBAoAAAAAAKiydlYAAAAAAAAAAAAAAAAXABwAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9VVAkAA1x/G2RyfxtkdXgLAAEEAAAAAAQAAAAAUEsDBBQACAAIAKiydlYAAAAAAAAAAPIAAAArABwAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9iYWNrZW5kdXJsLnBvbGljeXhtbFVUCQADXH8bZFx/G2R1eAsAAQQAAAAABAAAAABdjjsOwjAMhndOEWVvU7aq6mMBRqZygJAYiEidKE4LvT2pCkIwWfb/8Fd3z8GyCQIZhw3f5gVngMppg9eGn/pDVvKu3dTeWaMMULthbF1mto5+9pCcBGEHF4Og+Vs4yiEJZ6nugHoM9nPvYfBWxr/QUpyqyUm/R+2dwdjeYvSVEMstORNkhg4J1Bggj85ZymlSVVmUhXhQLX6yC6dYHyZ88eV/AVBLBwgyw5h4pAAAAPIAAABQSwECHgMKAAAAAACosnZWAAAAAAAAAAAAAAAAFwAYAAAAAAAAABAA7UEAAAAAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9VVAUAA1x/G2R1eAsAAQQAAAAABAAAAABQSwECHgMUAAgACACosnZWMsOYeKQAAADyAAAAKwAYAAAAAAABAAAApIFRAAAAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9iYWNrZW5kdXJsLnBvbGljeXhtbFVUBQADXH8bZHV4CwABBAAAAAAEAAAAAFBLBQYAAAAAAgACAM4AAABqAQAAAAA=
