apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: create-customer-policy
spec:
  type: policyproject
  contents: UEsDBAoAAAAAAH2hXFYAAAAAAAAAAAAAAAAXABwAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9VVAkAAw5g/mNDYP5jdXgLAAEE/v8AAAT+/wAAUEsDBBQACAAIAH2hXFYAAAAAAAAAAPIAAAArABwAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9iYWNrZW5kdXJsLnBvbGljeXhtbFVUCQADDmD+Yw5g/mN1eAsAAQT+/wAABP7/AABdjjsOwjAMhndOEWVvU7aq6mMBRqZygJAYiEidKE4LvT2pCkIwWfb/8Fd3z8GyCQIZhw3f5gVngMppg9eGn/pDVvKu3dTeWaMMULthbF1mto5+9pCcBGEHF4Og+Vs4yiEJZ6nugHoM9nPvYfBWxr/QUpyqyUm/R+2dwdjeYvSVEMstORNkhg4J1Bggj85ZymlSVVmUhXhQLX6yC6dYHyZ88eV/AVBLBwgyw5h4pAAAAPIAAABQSwECHgMKAAAAAAB9oVxWAAAAAAAAAAAAAAAAFwAYAAAAAAAAABAA7UEAAAAAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9VVAUAAw5g/mN1eAsAAQT+/wAABP7/AABQSwECHgMUAAgACAB9oVxWMsOYeKQAAADyAAAAKwAYAAAAAAABAAAApIFRAAAAY3JlYXRlLWN1c3RvbWVyLXBvbGljeS9iYWNrZW5kdXJsLnBvbGljeXhtbFVUBQADDmD+Y3V4CwABBP7/AAAE/v8AAFBLBQYAAAAAAgACAM4AAABqAQAAAAA=
